---

- name: delete rabbitmq guest user
  rabbitmq_user:
    name: guest
    tags: 'administrator'
    state: absent
  run_once: yes

- name: creating rabbitmq users
  rabbitmq_user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    vhost: "{{ item.vhost }}"
    configure_priv: "{{ item.configure_priv }}"
    read_priv: "{{ item.read_priv }}"
    write_priv: "{{ item.write_priv }}"
    tags: "{{ item.tags }}"
    state: present
  run_once: yes
  with_items: "{{ rabbitmq_users }}"

