---

- name: restarting rabbitmq-server on master
  service:
    name: rabbitmq-server
    state: restarted

# register **cluster_master** to indicate the node is clustered
- name: starting rabbitmq app on master
  command: rabbitmqctl start_app
