---

- name: sending sigterm to any running rabbitmq processes
  shell: pkill -u rabbitmq || true

- name: restarting rabbitmq-server
  service:
    name: rabbitmq-server
    state: restarted

- name: stopping rabbitmq app
  command: rabbitmqctl stop_app

- name: resetting rabbitmq app
  command: rabbitmqctl reset

# on none rabbitmq_master node, register **cluster_joined** to indicate the node is clustered
- name: joining rabbitmq cluster
  command: rabbitmqctl join_cluster rabbit@{{ hostvars[rabbitmq_master_addr]['ansible_hostname'] }}

- name: starting rabbitmq app
  command: rabbitmqctl start_app
