# zabbix_release: "zabbix-release-3.0-1.el7.noarch.rpm"
zabbix_release: "zabbix-release-3.2-1.el7.noarch.rpm"

#    /usr/share/doc/zabbix-server-mysql-3.0.3/create.sql.gz
zabbix_mysql_script_file: "/usr/share/doc/zabbix-server-mysql-3.2.4/create.sql.gz"


# 
gnutls: "gnutls-3.1.18-8.el7.x86_64.rpm"

zabbix_db_host: 127.0.0.1
zabbix_db_port: 3306
zabbix_db_name: zabbix
zabbix_db_user: zabbix
zabbix_db_pass: zabbix
zabbix_time_zone: "Asia/Shanghai"
