# some releases provide 'mysql', some provide 'mysqld'
ps57_mysql_service: mysqld

ps57_mysql_root_pass: "mysql"
ps57_mysql_repl_user: "repl"
ps57_mysql_repl_pass: "repl"
ps57_datadir: /var/lib/mysql
ps57_stream_port: 9999

# use this fact name to derive the ip address 
# for use of connection between master and slave.
ps57_ms_ip_fact_name: 'ansible_default_ipv4'

# leave this empty if you only apply this role to one target
ps57_mysql_master_host: ''
ps57_mysql_slave_host: ''

db_listen_addr: 0.0.0.0

ps57_packages:
  - Percona-Server-server-57
  - percona-xtrabackup
  - MySQL-python
  - nc
  - socat

_download_packages: "{{ ps57_packages | join (' ') }}"
