---

- name: transfer the define libvirt secret script
  copy: src=define-libvirt-secret.sh dest=/tmp/define-libvirt-secret.sh mode=755

# Note: the provided envrionment variables will be used by the script.
- name: define libvirt secret
  shell: bash /tmp/define-libvirt-secret.sh
  environment:
    osdm_ceph_libvirt_uuid_secret: "{{ osdm_ceph_libvirt_uuid_secret }}"

- name: remove the temporary script file
  file: path=/tmp/define-libvirt-secret.sh state=absent
