---

- name: install nova on controller
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - "{{ os_nova_controller_packages }}"

- name: install nova-network on controller
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - "{{ os_nova_network_packages }}"
  when: osdm_network_mode == 'nova-network' and not osdm_use_multihost

