---

- name: install nova on compute
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - "{{ os_nova_compute_packages }}"

- name: install nova-network on compute
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - "{{ os_nova_network_packages }}"
  when: osdm_network_mode == 'nova-network' and osdm_use_multihost

