---

- name: transfer script
  copy: src=create-provider-networks.sh dest=/tmp/create-provider-networks.sh

# Note: the provided envrionment variables will be used by the script.
- name: create provider networks
  shell: bash /tmp/create-provider-networks.sh
  environment:
    OS_USERNAME: admin
    OS_PASSWORD: "{{ osdm_user_admin_pass }}"
    OS_PROJECT_NAME: admin
    OS_USER_DOMAIN_NAME: default
    OS_PROJECT_DOMAIN_NAME: default
    OS_AUTH_URL: "http://{{ osdm_os_keystone_mgmt_ip }}:35357/v3"
    # OS_TOKEN: "{{ osdm_admin_token }}"
    # OS_URL: "http://{{ osdm_os_keystone_mgmt_ip }}:35357/v3"
    OS_IDENTITY_API_VERSION: "{{ osdm_user_use_identity_version }}"

    osdm_ft_pro_flat: "{{ osdm_ft_pro_flat }}"
    osdm_ft_pro_flat_range: "{{ osdm_ft_pro_flat_range }}"
    osdm_ft_pro_flat_gateway: "{{ osdm_ft_pro_flat_gateway }}"
    osdm_ft_pro_flat_pool_start: "{{ osdm_ft_pro_flat_pool_start }}"
    osdm_ft_pro_flat_pool_end: "{{ osdm_ft_pro_flat_pool_end }}"

    osdm_ft_pro_vlan1: "{{ osdm_ft_pro_vlan1 }}"
    osdm_ft_pro_vlan1_range: "{{ osdm_ft_pro_vlan1_range }}"
    osdm_ft_pro_vlan1_gateway: "{{ osdm_ft_pro_vlan1_gateway }}"
    osdm_ft_pro_vlan1_pool_start: "{{ osdm_ft_pro_vlan1_pool_start }}"
    osdm_ft_pro_vlan1_pool_end: "{{ osdm_ft_pro_vlan1_pool_end }}"

    osdm_ft_pro_vlan2: "{{ osdm_ft_pro_vlan2 }}"
    osdm_ft_pro_vlan2_range: "{{ osdm_ft_pro_vlan2_range }}"
    osdm_ft_pro_vlan2_gateway: "{{ osdm_ft_pro_vlan2_gateway }}"
    osdm_ft_pro_vlan2_pool_start: "{{ osdm_ft_pro_vlan2_pool_start }}"
    osdm_ft_pro_vlan2_pool_end: "{{ osdm_ft_pro_vlan2_pool_end }}"

- name: remove the temporary file
  file: path=/tmp/create-provider-networks.sh state=absent
