---

- name: using rsyslog to configure keepalived.log
  copy: src=rsyslog-keepalived.conf dest=/etc/rsyslog.d/keepalived.conf
# restorecon -R /etc/rsyslog.d/

- name: copy keepalived scripts
  copy: src={{ item }} dest=/usr/libexec/keepalived/{{ item }}
  with_items:
    - keepalived-status-change.sh
    - keepalived-status-change-to-master.sh
    - keepalived-status-change-to-backup.sh

- name: template keepalived.conf
  template: src=keepalived.conf.j2 dest=/etc/keepalived/keepalived.conf backup=yes

- name: start keepalived service
  service: name=keepalived state=restarted enabled=yes
