---

- name: avoid conflict
  yum: name={{ item }} state=absent disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - mysql-libs
    - mariadb-libs

- name: install Percona-XtraDB-Cluster
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - "{{ pxc56_packages }}"
