---

- name: add trove database
  mysql_db:
    login_host: "{{ osdm_mysql_mgmt_ip }}"
    login_user: root
    login_password: "{{ osdm_mysql_root_pass }}"
    name: "{{ item }}"
    state: present
    encoding: utf8
  with_items:
    - trove

- name: create trove db user/pass
  mysql_user:
    login_host: "{{ osdm_mysql_mgmt_ip }}"
    login_user: root
    login_password: "{{ osdm_mysql_root_pass }}"
    name: "{{ osdm_os_trove_db_user }}"
    host: "{{ item }}"
    password: "{{ osdm_os_trove_db_pass }}"
    priv: "trove.*:ALL PRIVILEGES"
    state: present
  with_items:
   - 'localhost'
   - '%'

- name: populate trove database
  shell: su trove -s /bin/sh -c "trove-manage db_sync"
  tags:
    - db_sync
