---

- name: make sure ceph-deploy package installed
  yum: name=ceph-deploy state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}

- name: check if ceph-deploy dir exists
  stat: path={{ ceph_deploy_dir }}
  register: ceph_deploy_dir

- name: fail when ceph-deploy dir not exist
  fail: 
    msg: "Could not find ceph-deploy in {{ ceph_deploy_dir }}"
  when: not ceph_deploy_dir.stat.exists

#- name: add osds - disk zap
#  shell: "cd {{ ceph_deploy_dir }};
#          ceph-deploy --overwrite-conf disk zap {% for osd in ceph_deploy_osd_disks %} {{ osd.split(':')[0:2]|join(':') }} {% endfor %}
#         "

- name: make sure owner of journal disk
  shell: chown ceph.ceph "/dev/{{ item.split(':')[2] }}"
  delegate_to: "{{ item.split(':')[0] }}"
  when: item.split(':')|length == 3
  with_items: "{{ ceph_deploy_osd_disks }}"

- name: add osds - osd create
  shell: "cd {{ ceph_deploy_dir }};
          ceph-deploy --overwrite-conf disk zap {{ item.split(':')[0:2]|join(':') }};
          ceph-deploy --overwrite-conf osd create {{ item }};
         "
  with_items: "{{ ceph_deploy_osd_disks }}"

# do not use the following syntax
# ceph-deploy --overwrite-conf osd create {% for osd in ceph_deploy_osd_disks %} {{ osd }} {% endfor %}
