---

- name: set fact osdm_os_admin_if_addr
  set_fact: "{{ item.key }}={{ item.value }}"
  with_dict:
    osdm_os_admin_if_addr: "{{ hostvars[inventory_hostname][osdm_ansible_os_admin_if].ipv4.address }}/{{ hostvars[inventory_hostname][osdm_ansible_os_admin_if].ipv4.netmask }}"

- name: set fact osdm_os_admin_if_<ip,prefix,netmask>
  set_fact: "{{ item.name }}={{ item.value }}"
  with_items:
    - { name: 'osdm_os_admin_if_ip', value: "{{ osdm_os_admin_if_addr | ipaddr('address') }}" }
    - { name: 'osdm_os_admin_if_prefix', value: "{{ osdm_os_admin_if_addr | ipaddr('prefix') }}" }
    - { name: 'osdm_os_admin_if_netmask', value: "{{ osdm_os_admin_if_addr | ipaddr('netmask') }}" }

- name: set fact osdm_os_admin_if_ipv4 dict
  set_fact:
    osdm_os_admin_if_ipv4: "{{ osdm_os_admin_if_ipv4 | default({}) | combine({item.key: item.value}) }}"
  with_items:
    - { key: 'address', value: "{{ osdm_os_admin_if_addr | ipaddr('address') }}" }
    - { key: 'prefix', value: "{{ osdm_os_admin_if_addr | ipaddr('prefix') }}" }
    - { key: 'netmask', value: "{{ osdm_os_admin_if_addr | ipaddr('netmask') }}" }
  #no_log: true

- debug: var=osdm_os_admin_if_ipv4
