---

- name: caculate out osdm_ipmi_lan_addr
  shell: /usr/bin/generate_new_addr.py {{ osdm_os_admin_if_addr }} {{ osdm_ipmi_lan_net }}
  register: ipmi_addr_ip_info

- name: set fact osdm_ipmi_lan_addr
  set_fact: "{{ item.name }}={{ item.value }}"
  with_items:
    - { name: 'osdm_ipmi_lan_addr', value: "{{ ipmi_addr_ip_info.stdout_lines[0] }}" }

- name: set fact osdm_ipmi_lan_ip
  set_fact: "{{ item.name }}={{ item.value }}"
  with_items:
    - { name: 'osdm_ipmi_lan_ip', value: "{{ osdm_ipmi_lan_addr | ipaddr('address') }}" }
    - { name: 'osdm_ipmi_lan_prefix', value: "{{ osdm_ipmi_lan_addr | ipaddr('prefix') }}" }
    - { name: 'osdm_ipmi_lan_netmask', value: "{{ osdm_ipmi_lan_addr | ipaddr('netmask') }}" }

- name: set fact osdm_ipmi_lan_ipv4 dict
  set_fact:
    osdm_ipmi_lan_ipv4: "{{ osdm_ipmi_lan_ipv4 | default({}) | combine({item.key: item.value}) }}"
  with_items:
    - { key: 'address', value: "{{ osdm_ipmi_lan_addr | ipaddr('address') }}" }
    - { key: 'prefix', value: "{{ osdm_ipmi_lan_addr | ipaddr('prefix') }}" }
    - { key: 'netmask', value: "{{ osdm_ipmi_lan_addr | ipaddr('netmask') }}" }
  no_log: true
