---

- name: install zabbix packages on proxy
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - "{{ zabbix_proxy_packages }}"
