---

- name: install ceph
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - "{{ ceph_packages_base }}"

# CentOS 7.2 install parted 3.1, but we need parted 3.2 due to bug:
# http://tracker.ceph.com/issues/15176
- name: transfer parted
  copy: src=parted-3.2-16.fc22.x86_64.rpm dest=/tmp/parted-3.2-16.fc22.x86_64.rpm

- name: update parted
  shell: rpm -qa | grep -sq parted-3.2 || rpm -Uvh /tmp/parted-3.2-16.fc22.x86_64.rpm

- name: delete temporary file
  file: path=/tmp/parted-3.2-16.fc22.x86_64.rpm state=absent

- name: copy ceph-rest-api.service
  copy: src=ceph-rest-api.service dest=/etc/systemd/system/ceph-rest-api.service
