---

- include: repo.yml
  tags:
    - repo

- include: download.yml
  when: osdm_download_packages
  tags:
    - download

- include: install-base.yml
  tags:
    - install

- include: install-radosgw.yml
  when: ceph_pkg_radosgw
  tags:
    - install

- include: install-fs.yml
  when: ceph_pkg_fs
  tags:
    - install
