---

- name: copy Ceph gpg key
  copy: src=ceph.key dest=/tmp/ceph.key

- name: import Ceph gpg key
  rpm_key: state=present key=/tmp/ceph.key

- name: prepare Ceph release repo
  copy: src={{ item }}.{{ osdm_install_repo_source }} dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - ceph.repo
