---

- include: repo.yml
  tags:
    - repo

- include: download.yml
  when: osdm_download_packages
  tags:
    - download

- include: install.yml
  tags:
    - install

- include: start.yml
  tags:
    - start

- include: setup-master-slave.yml
  when: inventory_hostname == ps56_mysql_master_host or inventory_hostname == ps56_mysql_slave_host
  static: no
  tags:
    - setup-master-slave
