---

- name: copy percona gpg key
  copy: src=percona.key dest=/tmp/percona.key

- name: import percona gpg key
  rpm_key: state=present key=/tmp/percona.key

- name: prepare percona release repo
  copy: src={{ item }}.{{ osdm_install_repo_source }} dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - percona.repo
