ceph_deploy_dir: /root/ceph-deploy

# This variable control wether to use a separate dedicated network for the ceph
# cluster network. Default false means the public network and the cluster network
# of the cluster use the same network.
ceph_deploy_ceph_cluster_network_dedicated: false

# should be provided by playbook or environment vars
ceph_deploy_ceph_conf_params: []

#
# CAUTION: DO NOT PUT `osd_crush_update_on_start` parameter on ceph.conf regardless of true or false.
# CAUTION: `mon_osd_auto_mark_in` should not set `false`.
# There's no space in the item of the list (`osd_journal_size = 5120` is wrong).
#

_preset_ceph_conf_params:
  - osd_journal_size=5120
  - osd_pool_default_size=3
  - max_open_files=1048576
  - mon_osd_full_ratio=0.95
  - mon_osd_nearfull_ratio=0.85
  - mon_osd_auto_mark_in=false
  - mon_osd_auto_mark_auto_out_in=false
  - mon_osd_auto_mark_new_in=true
  - mon_osd_adjust_heartbeat_grace=false
  - mon_osd_adjust_down_out_interval=false
  - osd_max_write_size=512
  - osd_client_op_priority=63
  - osd_client_message_cap=65536
  - osd_client_message_size_cap=536870912
  - osd_recovery_delay_start=60
  - osd_recovery_threads=4
  - osd_recovery_op_priority=1
  - osd_recovery_max_active=3
  - osd_recovery_max_single_start=1
  - osd_op_threads=16
  - osd_max_backfills=3
  - osd_backfill_scan_min=64
  - osd_backfill_scan_max=512
  - osd_backfill_full_ratio=0.85
  - osd_backfill_retry_interval=30
  - osd_disk_threads=8
  - osd_scrub_begin_hour=0
  - osd_scrub_end_hour=8
  - osd_max_push_objects=100
  - osd_map_cache_size=1024
  - osd_mount_options_xfs="rw,noexec,nodev,noatime,nodiratime,nobarrier"
  - objecter_inflight_ops=10240
  - objecter_inflight_op_bytes=1048576000
  - journal_max_write_bytes=1048576000
  - journal_max_write_entries=10000
  - journal_queue_max_ops=65536
  - journal_queue_max_bytes=536870912
  - filestore_op_threads=16
  - filestore_queue_max_ops=65536
  - filestore_queue_max_bytes=536870912
  - filestore_queue_committing_max_ops=65536
  - filestore_queue_committing_max_bytes=536870912
  - filestore_max_sync_interval=15
  - filestore_min_sync_interval=9
