---

- name: make sure ceph-deploy package installed
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - ceph-deploy

- name: create dir for ceph-deploy
  file: path={{ ceph_deploy_dir }} state=directory

- name: check the existence of file ceph.conf in deploy directory
  stat: path={{ ceph_deploy_dir }}/ceph.conf
  register: ceph_conf_exists

- name: failed the role if ceph.conf is found in deploy directory
  fail:
    msg: "Find ceph.conf in {{ ceph_deploy_dir }}, may be there already exists an ceph cluster.
          If you really want to deploy a new cluster, you should manually clear the deploy directory.
          And you might require to execute the following commands to clear something.
          ceph-deploy purge <host>,
          ceph-deploy purgedata <host>
          "
  when: ceph_conf_exists.stat.exists

- name: create a new ceph cluster
  shell:  cd {{ ceph_deploy_dir }};
          ceph-deploy new \
          --cluster-network {% if ceph_deploy_ceph_cluster_network_dedicated -%}
                                {{ osdm_os_stor_net }}
                            {%- else -%}
                                {{ osdm_os_mgmt_net }}
                            {%- endif %}    \
          {% for mon in groups['ceph-mon'] %} {{ hostvars[mon]['ansible_hostname'] }} {% endfor %}

# We don't use --public-network option.
# --public-network {{ osdm_os_mgmt_net }}

- name: update preset ceph conf parameters
  lineinfile:
    dest: "{{ ceph_deploy_dir }}/ceph.conf"
    regexp: ".*{{ item.split('=')[0] }}.*$"
    line: "{{ item.split('=')[0] }} = {{ item.split('=')[1] }}"
    state: present
  with_items: "{{ _preset_ceph_conf_params | default([]) }}"
  tags: update-ceph-conf

- name: update ceph conf parameters provided by role's vars
  lineinfile:
    dest: "{{ ceph_deploy_dir }}/ceph.conf"
    regexp: ".*{{ item.split('=')[0] }}.*$"
    line: "{{ item.split('=')[0] }} = {{ item.split('=')[1] }}"
    state: present
  with_items: "{{ ceph_deploy_ceph_conf_params | default([]) }}"
  tags: update-ceph-conf
