# send vrrip packet through this interface
keepalived_vrrp_interface: eth0

keepalived_chk_proxy_enable: false

keepalived_packages:
  - keepalived
  - haproxy

_download_packages: "{{ keepalived_packages | join(' ') }}"
