---

- include: download.yml
  when: osdm_download_packages
  tags: download

- include: install.yml
  tags: install

- include: start.yml
  tags: start

- include: create-cluster.yml
  when: groups[pacemaker_cluster_node_group]|length > 0
  run_once: true
  static: no
  tags: create-cluster
