---

- name: start pcsd service
  service: name=pcsd  state=started enabled=yes

- name: generate hacluster password
  shell: python -c "import crypt; print crypt.crypt('{{ pacemaker_hacluster_password }}')"
  register: _password

- name: set hacluster password
  user: name=hacluster password={{ _password.stdout_lines[0] }} createhome=no

