---

- name: update /etc/hosts on cluster proxy
  lineinfile:
    backup: yes
    dest: /etc/hosts
    regexp: ".*{{ hostvars[item]['ansible_hostname'] }}$"
    line: "{{ item }} {{ hostvars[item]['ansible_hostname'] }}"
    state: present
  with_items: "{{ groups['all'] }}"
