---

- name: create the influxdb database
  shell: /usr/bin/influx -username {{ influxdb_admin_user }} -password '{{ influxdb_admin_pass }}' -execute "create database {{ item }}"
  with_items: "{{ influxdb_databases }}"
