---

- name: create the influxdb database and normal user
  shell: /usr/bin/influx -username {{ influxdb_admin_user }} -password '{{ influxdb_admin_pass }}' -execute "create user {{ item.username }} with password '{{ item.password }}'; grant {{ item.privilege }} on {{ item.database }} to {{ item.username }}"
  with_items: "{{ influxdb_users }}"
