---

- name: create grafana database
  mysql_db:
    name: "{{ grafana_db_name }}"
    state: present
    login_host: "{{ grafana_db_host }}"
    login_port: "{{ grafana_db_port }}"

- name: create grafana db user/pass
  mysql_user:
    name: "{{ grafana_db_user }}"
    host: '%'
    password: "{{ grafana_db_pass }}"
    priv: "{{ grafana_db_name }}.*:ALL PRIVILEGES"
    state: present
    login_host: "{{ grafana_db_host }}"
    login_port: "{{ grafana_db_port }}"
