---

- include: repo.yml
  tags:
    - repo

- include: download.yml
  when: osdm_download_packages
  tags:
    - download

- include: install.yml
  tags:
    - install

- include: init-db.yml
  tags:
    - init-db

- include: start.yml
  tags:
    - start

- include: import-datasource.yml
  tags: import-datasource

- include: import-dashboard.yml
  tags: import-dashboard
