---

- name: copy grafana gpg key
  copy: src={{ item }} dest=/tmp/{{ item }}
  with_items:
    - grafana.key
    - packagecloud.key

- name: import grafana gpg key
  rpm_key: state=present key=/tmp/{{ item }}
  with_items:
    - grafana.key
    - packagecloud.key

- name: prepare grafana release repo
  copy: src={{ item }}.{{ osdm_install_repo_source }} dest=/etc/yum.repos.d/{{ item }}
  with_items:
    - grafana.repo
