---

- name: setup rsyslog for haproxy
  copy: src=rsyslog-haproxy.conf dest=/etc/rsyslog.d/haproxy.conf
  notify: restart rsyslog
# restorecon -R /etc/rsyslog.d/

- name: templates basic haproxy.cfg
  template: src=haproxy.cfg.j2 dest=/etc/haproxy/haproxy.cfg backup=yes
  notify:
    - restart haproxy

#- name: template haproxy service.cfg
#  template: src=service.cfg dest=/etc/haproxy/haproxy.d/service.cfg backup=yes
#  notify:
#    - restart haproxy

- name: make haproxy bindable on non local address
  sysctl: name=net.ipv4.ip_nonlocal_bind value=1 sysctl_set=yes state=present
  when: haproxy_bind_on_local|bool

- name: start haproxy service
  service: name=haproxy state=restarted
