---

- hosts: "{{ _hosts }}"
  tasks:
    - name: execute createrepo
      shell: createrepo {{ osdm_local_repo_packages_proxy }}/packages/
    - name: fetch from cluster proxy node to ansible local
      synchronize:
        mode: pull
        src: "{{ osdm_local_repo_packages_proxy }}/packages/"
        dest: "{{ osdm_local_repo_packages }}/packages/"
        delete: yes
        recursive: yes
        rsync_opts:
          - "{{ osdm_ansible_rsync_opts }}"
