---

- name: install collectd-virt package
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - collectd-virt
  when: collectd_virt_enable

- name: install collectd-ceph package
  yum: name={{ item }} state=present disablerepo={{ osdm_disable_repo }} enablerepo={{ osdm_enable_repo }}
  with_items:
    - collectd-ceph
  when: collectd_ceph_enable
